### ISSUE TITLE
mop_mod Nanocompore eventalign_collapse requires three threads, but uses only one by default. How to adjust tools_opt.tsv?

### ISSUE THREAD

**Issue by miles-jon** [biocorecrg/MOP2#54]
Hi there, 
 
I am trying to use the mop_mod pipeline with some data that I have already piped into the same output with mop_preprocess. I am using docker as my virtualization software. 
However, the nanocompore part of the nextflow pipeline throws up the following error in the eventalign stage (pulled from the log.txt file) 
 
[8f/fcd29c] Submitted process > compore_polish_flow:mean_per_pos (25per_IVT)
[cb/09af45] Submitted process > compore_polish_flow:NANOPOLISH_EVENTALIGN:eventalignCollapse (25per_IVT)
[2f/188da8] Submitted process > compore_polish_flow:NANOPOLISH_EVENTALIGN:eventalignCollapse (no_sample)
ERROR ~ Error executing process > 'compore_polish_flow:NANOPOLISH_EVENTALIGN:eventalignCollapse (25per_IVT)'
 
Caused by:
  Process `compore_polish_flow:NANOPOLISH_EVENTALIGN:eventalignCollapse (25per_IVT)` terminated with an error exit status (1)
 
Command executed:
 
  zcat 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_27.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_41.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_16.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_5.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_23.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_19.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_4.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_31.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_28.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_2.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_7.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_34.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_38.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_12.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_13.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_24.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_20.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_8.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_0.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_1.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_42.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_11.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_21.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_6.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_40.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_22.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_35.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_33.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_18.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_39.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_29.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_17.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_37.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_36.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_26.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_32.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_9.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_25.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_15.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_3.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_14.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_10.fast5_event_align.tsv.gz 25per_IVT_AQJ052_pass_ae7f1f60_c0908c38_30.fast5_event_align.tsv.gz | awk '!(/^contig/ && NR>1)' | tee   >(pigz -p 1 -9 - > 25per_IVT_combined.eventalign.tsv.gz) | NanopolishComp Eventalign_collapse -t 1 -o 25per_IVT_collapsed_align_events
 
Command exit status:
  1
 
Command output:
  (empty)
 
Command error:
  Checking arguments
  Traceback (most recent call last):
    File "/usr/local/python/versions/3.6.3/bin/NanopolishComp", line 8, in <module>
      sys.exit(main())
    File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/NanopolishComp/__main__.py", line 65, in main
      args.func(args)
    File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/NanopolishComp/__main__.py", line 80, in Eventalign_collapse_main
      quiet = args.quiet)
    File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/NanopolishComp/Eventalign_collapse.py", line 106, in __init__
      raise ValueError ("At least 3 threads required")
  ValueError: At least 3 threads required
 
Work dir:
  /home/jon/MOP2/mop_mod/work/cb/09af4521356581ae83a301f25c9762
 
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
 
-- Check '.nextflow.log' file for details
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2023-12-18T15:49:38.553934Z
Finished at 2023-12-18T16:28:36.529021Z
Time elapsed: 38m 58s
Execution status: failed
WARN: Killing running tasks (2)
 
It looks like the Eventalign command that's being called has a default thread value (1) that is below it's own required minimum (3). 
I have attempted a couple of times to solve this problem using the tools_opt.tsv file in the mop_mod folder, trying "-t 3", "-threads 3", or as below:
#flows  tool    extrapars
epinano epinano ""
nanocompore     nanopolish      "NanopolishComp Eventalign_collapse -t 3"
nanocompore     nanocompore     "--sequence_context 2 --downsample_high_coverage 10000"
tombo_resquiggling      tombo   ""
tombo_msc       tombo   ""
tombo_lsc       tombo   ""
 
Whilst I am able to run the mop_mod pipeline without nanocompore by turning it off, and produce results for the tombo and epinano modules, I am not able to then pipe these through the mop_consensus pipeline., which quits after only checking and indexing the reference fasta. 
 
However these have not worked. 
How might I be able to adjust the parameters or the nextflow pipeline to allow the Eventalign_collapse command to use three threads as required? Will this full directory then be able to be piped into nanoconsensus? 
 
Thanks, 
 
Jon

**Comment by lucacozzuto** [comment]
Hi, which profile are you using? The number of CPUs for eventalign is defined in the labels: 'big_mem_cpus' and 'big_time_cpus'
